/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Window;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author DaVo
 */
public class Quiz extends javax.swing.JPanel {

    /**
     * Creates new form Quiz
     */
    private int wpm;
    public Quiz(int wpm) {
        initComponents();
        this.wpm = wpm;
        this.wpmLabel.setText(wpm+"");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        False1 = new javax.swing.JRadioButton();
        Ans1 = new javax.swing.JRadioButton();
        False2 = new javax.swing.JRadioButton();
        False3 = new javax.swing.JRadioButton();
        False4 = new javax.swing.JRadioButton();
        Ans2 = new javax.swing.JRadioButton();
        False5 = new javax.swing.JRadioButton();
        False6 = new javax.swing.JRadioButton();
        Ans3 = new javax.swing.JRadioButton();
        False7 = new javax.swing.JRadioButton();
        Ans4 = new javax.swing.JRadioButton();
        False8 = new javax.swing.JRadioButton();
        False9 = new javax.swing.JRadioButton();
        False10 = new javax.swing.JRadioButton();
        Ans5 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        False17 = new javax.swing.JRadioButton();
        False18 = new javax.swing.JRadioButton();
        False15 = new javax.swing.JRadioButton();
        False16 = new javax.swing.JRadioButton();
        jRadioButton20 = new javax.swing.JRadioButton();
        Ans9 = new javax.swing.JRadioButton();
        False19 = new javax.swing.JRadioButton();
        Ans10 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        False11 = new javax.swing.JRadioButton();
        Ans6 = new javax.swing.JRadioButton();
        False12 = new javax.swing.JRadioButton();
        False13 = new javax.swing.JRadioButton();
        Ans7 = new javax.swing.JRadioButton();
        Ans8 = new javax.swing.JRadioButton();
        False14 = new javax.swing.JRadioButton();
        sumbitAns = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        finalScore = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        wpmLabel = new javax.swing.JLabel();

        buttonGroup1.add(False1);
        False1.setText("A) higher speed and worse reading comprehension ");

        buttonGroup1.add(Ans1);
        Ans1.setText("B) higher speed and better reading comprehension ");

        buttonGroup1.add(False2);
        False2.setText("C) higher speed and same reading comprehension ");

        buttonGroup2.add(False3);
        False3.setText("A) Are average readers ");

        buttonGroup2.add(False4);
        False4.setText("B) Are the majority of readers ");

        buttonGroup2.add(Ans2);
        Ans2.setText("C) Are the 1 % minority ");

        buttonGroup3.add(False5);
        False5.setText("A) 120 wpm ");

        buttonGroup3.add(False6);
        False6.setText("B) 150 wpm ");

        buttonGroup3.add(Ans3);
        Ans3.setText("C) 200 wpm ");

        buttonGroup4.add(False7);
        False7.setText("A) 50 % ");

        buttonGroup4.add(Ans4);
        Ans4.setText("B) 60 % ");

        buttonGroup4.add(False8);
        False8.setText("C) 85 % ");

        buttonGroup5.add(False9);
        False9.setText("A) 10 seconds (near record time) ");

        buttonGroup5.add(False10);
        False10.setText("B) 35 seconds (jogging) ");

        buttonGroup5.add(Ans5);
        Ans5.setText("C) 70 seconds (walking speed) ");

        jLabel1.setText("Q1. Compared to average reader, the accomplished reader reads with? ");

        jLabel2.setText("Q2. Readers reading above 1000 wpm? ");

        jLabel3.setText("Q3. The average reading speed is around? ");

        jLabel4.setText("Q4. The average reader comprehension is around? ");

        jLabel5.setText("Q5. A sprinter running as the average reader reads, runs 100m in? ");

        buttonGroup9.add(False17);
        False17.setText("A) Spelling-checkers ");

        buttonGroup9.add(False18);
        False18.setText("B) More ergonomic keyboards ");

        buttonGroup8.add(False15);
        False15.setText("B) Improve reading ");

        buttonGroup8.add(False16);
        False16.setText("C) Buy a larger screen ");

        buttonGroup10.add(jRadioButton20);
        jRadioButton20.setText("B) Consistent practice ");

        buttonGroup9.add(Ans9);
        Ans9.setText("C) Progress in voice recognition ");

        buttonGroup10.add(False19);
        False19.setText("A) Rapid results ");

        buttonGroup10.add(Ans10);
        Ans10.setText("C) Deep enough explanations ");

        jLabel6.setText("Q8. Most computer users want to? ");

        jLabel7.setText("Q9. What will lessen the importance of fast typing? ");

        jLabel8.setText("Q6. Which is the most effective way to acquire knowledge from information? ");

        jLabel9.setText("Q7. The average speaking speed of a race driver is around? ");

        jLabel10.setText("Q10. A speed reading seminar or book lacks? ");

        buttonGroup6.add(False11);
        False11.setText("A) watching TV ");
        False11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                False11ActionPerformed(evt);
            }
        });

        buttonGroup6.add(Ans6);
        Ans6.setText("B) reading text ");

        buttonGroup6.add(False12);
        False12.setText("C) listening to a speaker ");

        buttonGroup7.add(False13);
        False13.setText("A) 120 mph ");

        buttonGroup7.add(Ans7);
        Ans7.setText("B) 150 wpm");

        buttonGroup8.add(Ans8);
        Ans8.setText("A) Improve typing ");

        buttonGroup7.add(False14);
        False14.setText("C) 200 wpm");

        sumbitAns.setText("Submit");
        sumbitAns.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sumbitAnsMouseClicked(evt);
            }
        });

        jLabel11.setText("Pratice Quiz");

        backButton.setText("Back");
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
        });

        finalScore.setText("-");

        jLabel12.setText("of 10");

        jLabel13.setText("WPM:");

        wpmLabel.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(Ans5)
                            .addComponent(False10)
                            .addComponent(False9)
                            .addComponent(False8)
                            .addComponent(Ans4)
                            .addComponent(False7)
                            .addComponent(Ans3)
                            .addComponent(False6)
                            .addComponent(False5)
                            .addComponent(Ans2)
                            .addComponent(False4)
                            .addComponent(False3)
                            .addComponent(False2)
                            .addComponent(Ans1)
                            .addComponent(False1)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backButton)
                                .addGap(125, 125, 125)
                                .addComponent(sumbitAns)
                                .addGap(45, 45, 45)
                                .addComponent(finalScore)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(47, 47, 47)
                                .addComponent(wpmLabel))
                            .addComponent(jLabel10)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(Ans10)
                            .addComponent(jRadioButton20)
                            .addComponent(False19)
                            .addComponent(Ans9)
                            .addComponent(False18)
                            .addComponent(False17)
                            .addComponent(False16)
                            .addComponent(False15)
                            .addComponent(Ans8)
                            .addComponent(False14)
                            .addComponent(Ans7)
                            .addComponent(False13)
                            .addComponent(False12)
                            .addComponent(Ans6)
                            .addComponent(False11)
                            .addComponent(jLabel9))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(False11)
                                .addGap(5, 5, 5)
                                .addComponent(Ans6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(False12)
                                .addGap(13, 13, 13)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(False13)
                                .addGap(5, 5, 5)
                                .addComponent(Ans7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(False14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6)
                                .addGap(2, 2, 2)
                                .addComponent(Ans8)
                                .addGap(5, 5, 5)
                                .addComponent(False15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(False16)
                                .addGap(9, 9, 9)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(False17)
                                .addGap(5, 5, 5)
                                .addComponent(False18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Ans9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10)
                                .addGap(2, 2, 2)
                                .addComponent(False19)
                                .addGap(5, 5, 5)
                                .addComponent(jRadioButton20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Ans10))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(False1)
                                .addGap(5, 5, 5)
                                .addComponent(Ans1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(False2)
                                .addGap(13, 13, 13)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(False3)
                                .addGap(5, 5, 5)
                                .addComponent(False4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Ans2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addGap(2, 2, 2)
                                .addComponent(False5)
                                .addGap(5, 5, 5)
                                .addComponent(False6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Ans3)
                                .addGap(9, 9, 9)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(False7)
                                .addGap(5, 5, 5)
                                .addComponent(Ans4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(False8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addGap(2, 2, 2)
                                .addComponent(False9)
                                .addGap(5, 5, 5)
                                .addComponent(False10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Ans5)))
                        .addGap(50, 50, 50)
                        .addComponent(backButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(finalScore)
                            .addComponent(jLabel12)
                            .addComponent(sumbitAns)
                            .addComponent(jLabel13)
                            .addComponent(wpmLabel))
                        .addGap(32, 32, 32))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void False11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_False11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_False11ActionPerformed

    private void sumbitAnsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sumbitAnsMouseClicked
        // TODO add your handling code here:
        int count = 0;
        if(Ans1.isSelected()==true){
            count++;
        }
        if(Ans2.isSelected()==true){
            count++;
        }
        if(Ans3.isSelected()==true){
            count++;
        }
        if(Ans4.isSelected()==true){
            count++;
        }
        if(Ans5.isSelected()==true){
            count++;
        }
        if(Ans6.isSelected()==true){
           count++; 
        }
        if(Ans7.isSelected()==true){
            count++;
        }if(Ans8.isSelected()==true){
            count++;
        }
        if(Ans9.isSelected()==true){
            count++;
        }if(Ans10.isSelected()==true){
            count++;
        }
        finalScore.setText(count+"");
        System.out.println(count);
        
    }//GEN-LAST:event_sumbitAnsMouseClicked

    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseClicked
        // TODO add your handling code here:
        Window w = SwingUtilities.getWindowAncestor(Quiz.this);
        w.setVisible(false);
    }//GEN-LAST:event_backButtonMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Ans1;
    private javax.swing.JRadioButton Ans10;
    private javax.swing.JRadioButton Ans2;
    private javax.swing.JRadioButton Ans3;
    private javax.swing.JRadioButton Ans4;
    private javax.swing.JRadioButton Ans5;
    private javax.swing.JRadioButton Ans6;
    private javax.swing.JRadioButton Ans7;
    private javax.swing.JRadioButton Ans8;
    private javax.swing.JRadioButton Ans9;
    private javax.swing.JRadioButton False1;
    private javax.swing.JRadioButton False10;
    private javax.swing.JRadioButton False11;
    private javax.swing.JRadioButton False12;
    private javax.swing.JRadioButton False13;
    private javax.swing.JRadioButton False14;
    private javax.swing.JRadioButton False15;
    private javax.swing.JRadioButton False16;
    private javax.swing.JRadioButton False17;
    private javax.swing.JRadioButton False18;
    private javax.swing.JRadioButton False19;
    private javax.swing.JRadioButton False2;
    private javax.swing.JRadioButton False3;
    private javax.swing.JRadioButton False4;
    private javax.swing.JRadioButton False5;
    private javax.swing.JRadioButton False6;
    private javax.swing.JRadioButton False7;
    private javax.swing.JRadioButton False8;
    private javax.swing.JRadioButton False9;
    private javax.swing.JButton backButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JLabel finalScore;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton20;
    private javax.swing.JButton sumbitAns;
    private javax.swing.JLabel wpmLabel;
    // End of variables declaration//GEN-END:variables
}
